# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vivienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_familia', models.CharField(max_length=100)),
                ('familia_beneficiada', models.BooleanField(default=False)),
                ('tenencia', models.CharField(choices=[('PR', 'Propia'), ('AL', 'Alquilada'), ('PA', 'Pagada'), ('HE', 'Heredada'), ('CE', 'Cedida')], max_length=2)),
                ('alquilada', models.FloatField()),
                ('pasaje', models.BooleanField(default=False)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vivienda.Vivienda')),
            ],
        ),
    ]
