# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo_familiar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(help_text='Cédula de Identidad del usuario', max_length=9, validators=[django.core.validators.RegexValidator('^[VE][\\d]{8}$', 'Introduzca un número de cédula válido. Solo se permiten números y una longitud de 8 carácteres. Se agrega un 0 si la longitud es de 7 carácteres.')])),
                ('telefono', models.CharField(help_text='Número telefónico de contacto con el usuario', max_length=18, validators=[django.core.validators.RegexValidator('^\\(\\+\\d{3}\\)-\\d{3}-\\d{7}$', 'Número telefónico inválido. Solo se permiten números y los símbolos: ( ) - +')])),
                ('correo', models.CharField(help_text='correo@correo.com', max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('parentesco', models.CharField(choices=[('JF', 'Jefe Familiar'), ('MA', 'Madre'), ('PA', 'Padre'), ('CN', 'Concubino(a)'), ('HI', 'Hijo(a)'), ('YE', 'Yerno(a)'), ('SU', 'Suegro(a)'), ('AB', 'Abuelo(a)'), ('NI', 'Nieto(a)'), ('HE', 'Hermano(a)'), ('CU', 'Cuñado(a)'), ('BI', 'Bisabuelo(a)'), ('BS', 'Bisnieto(a)'), ('TI', 'Tío(a)'), ('SO', 'Sobrino(a)'), ('PR', 'Primo(a)'), ('TA', 'Tio(a) Abuelo(a)'), ('AD', 'Adoptado(a)')], max_length=2)),
                ('estado_civil', models.CharField(choices=[('SO', 'Soltero(a)'), ('CA', 'Casado(a)'), ('CO', 'Concubino(a)'), ('DI', 'Divirciado(a)'), ('VI', 'Viudo(a)')], max_length=2)),
                ('grado_instruccion', models.CharField(choices=[('LA', 'Lactante'), ('PR', 'Preescolar'), ('1G', 'Primer Grado'), ('2G', 'Segundo Grado'), ('3G', 'Tercer Grado'), ('4G', 'Cuarto Grado'), ('5G', 'Quinto Grado'), ('6G', 'Sexto Grado'), ('7G', 'Septimo Grado'), ('8G', 'Octavo Grado'), ('9G', 'Noveno Grado'), ('1A', 'Primer Año Diversificado'), ('2A', 'Segundo Año Diversificado'), ('BA', 'Bachiller'), ('TM', 'Técnico Medio'), ('TS', 'Técnico Superior Universitario'), ('UN', 'Universitario')], max_length=2)),
                ('mision_educativa', models.CharField(choices=[('NI', 'Ninguna'), ('R1', 'Misión Robinson 1'), ('R2', 'Misión Robinson 2'), ('MR', 'Misión Rivas'), ('MS', 'Misión Sucre'), ('MA', 'Misión Alma Mater'), ('MC', 'Misión Ciencia'), ('PA', 'Misión Cultura Corazón Abierto'), ('MM', 'Misión Música')], max_length=2)),
                ('profesion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('ingreso', models.CharField(choices=[('NI', 'Ninguno'), ('ME', 'Menos de un Sueldo Mínimo'), ('1S', '1 Sueldo Mínimo'), ('M1', 'Más de 1 sueldo Mínimo'), ('2S', '2 Sueldos Mínimos'), ('M2', 'Más de 2 Sueldos Mínimos')], max_length=100)),
                ('deporte', models.CharField(max_length=100)),
                ('enfermedad', models.CharField(max_length=500)),
                ('discapacidad', models.CharField(max_length=500)),
                ('ley_consejo_comunal', models.BooleanField(default=False)),
                ('curso', models.CharField(max_length=100)),
                ('organizacion_comunitaria', models.CharField(max_length=500)),
                ('ocio', models.CharField(max_length=500)),
                ('mejorar_comunicacion', models.CharField(max_length=500)),
                ('inseguridad', models.CharField(max_length=500)),
                ('comentario', models.CharField(max_length=500)),
                ('grupo_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo_familiar.GrupoFamiliar')),
            ],
        ),
    ]
