# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('encuestador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/vivienda/')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('servicio_electrico', models.CharField(choices=[('DI', 'Directa'), ('CO', 'Compartida'), ('IL', 'Ilegal'), ('OT', 'Otros')], max_length=2)),
                ('situacion_sanitaria', models.CharField(choices=[('CL', 'Cloacas'), ('PS', 'Pozo Séptico'), ('CA', 'Campo Abierto'), ('LE', 'Letrina')], max_length=2)),
                ('disposicion_basura', models.CharField(choices=[('RD', 'Recolección Directa'), ('CO', 'Container'), ('QU', 'Quemada'), ('EN', 'Enterrada')], max_length=2)),
                ('tipo_vivienda', models.CharField(choices=[('CA', 'Casa'), ('AP', 'Apartamento'), ('QU', 'Quinta'), ('RA', 'Rancho'), ('HA', 'Habitación')], max_length=2)),
                ('tipo_techo', models.CharField(choices=[('AC', 'Acerolit'), ('AS', 'Asbesto'), ('CT', 'Carruzo y Teja'), ('PB', 'Plata Banda'), ('TE', 'Teja'), ('TJ', 'Tejalic'), ('ZI', 'Zinc'), ('OT', 'Otros')], max_length=2)),
                ('tipo_pared', models.CharField(choices=[('AD', 'Adobe'), ('BA', 'Bahareque'), ('BR', 'Barro'), ('BL', 'Bloque'), ('LA', 'Ladrillo'), ('PI', 'Piedra'), ('ZI', 'Zinc'), ('OT', 'Otros')], max_length=2)),
                ('pared_frizada', models.BooleanField(default=False)),
                ('tipo_piso', models.CharField(choices=[('TI', 'Tierra'), ('CE', 'Cemento'), ('GR', 'Granito'), ('CR', 'Cerámica'), ('BA', 'Baldosa'), ('MA', 'Madera'), ('TE', 'Terracota'), ('OT', 'Otors')], max_length=2)),
                ('tipo_cemento', models.CharField(choices=[('RO', 'Robusto'), ('PU', 'Pulido')], max_length=2, null=True)),
                ('condicion_vivienda', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('condicion_techo', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('condicion_pared', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('condicion_piso', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('condicion_ventilacion', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('condicion_iluminacion', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('accesibilidad_ambulatorio', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('accesibilidad_escuela', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('accesibilidad_liceo', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('accesibilidad_centro_abastecimiento', models.CharField(choices=[('B', 'Buena'), ('R', 'Regular'), ('M', 'Mala')], max_length=1)),
                ('numero_habitaciones', models.IntegerField()),
                ('numero_salas', models.IntegerField()),
                ('numero_banhos', models.IntegerField()),
                ('tiene_terreno', models.BooleanField()),
                ('metro_cuadrado', models.FloatField()),
                ('productivo', models.FloatField()),
                ('por_producir', models.FloatField()),
                ('riesgo_rio', models.BooleanField()),
                ('riesgo_quebrada', models.BooleanField()),
                ('riesgo_derrumbe', models.BooleanField()),
                ('riesgo_zona_sismica', models.BooleanField()),
                ('animales', models.CharField(max_length=500)),
                ('numero_vivienda', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=500)),
                ('consejo_comunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ConsejoComunal')),
                ('encuestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Encuestador')),
            ],
        ),
        migrations.AddField(
            model_name='imagen',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vivienda.Vivienda'),
        ),
    ]
