# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='coordenadas',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
