# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivienda', '0002_vivienda_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='coordenadas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
