# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivienda', '0003_auto_20170605_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='coordenadas',
            field=models.CharField(default='esto es una prueba', max_length=255),
        ),
    ]
