# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivienda', '0004_auto_20170605_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='coordenadas',
            field=models.CharField(max_length=255),
        ),
    ]
