# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivienda', '0005_auto_20170605_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
