# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 16:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(help_text='Cédula de Identidad del usuario', max_length=9, validators=[django.core.validators.RegexValidator('^[VE][\\d]{8}$', 'Introduzca un número de cédula válido. Solo se permiten números y una longitud de 8 carácteres. Se agrega un 0 si la longitud es de 7 carácteres.')])),
                ('telefono', models.CharField(help_text='Número telefónico de contacto con el usuario', max_length=20, validators=[django.core.validators.RegexValidator('^\\(\\d{3}\\)-\\d{3}-\\d{7}$', 'Número telefónico inválido. Solo se permiten números, y los signos + o -')])),
                ('correo', models.CharField(help_text='correo@correo.com', max_length=100)),
            ],
        ),
    ]
